### ISSUE TITLE
[Android Bootcamp] Project 3: Twi@er - Ready for Review #1

### ISSUE THREAD

**Issue by nagarakesh4** [nagarakesh4/TweetThis#1]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
@nagarakesh4 , please add a GIF file to your readme with a complete walkthrough of all the completed stories.

cc: @nesquena

**Comment by nagarakesh4** [comment]
@nesquena , the LiceCAP isn't working properly, they have a bug in their product. Here is the link of their issue I am facing - [https://github.com/justinfrankel/licecap/issues/6](https://github.com/justinfrankel/licecap/issues/6).

I have already added URL to youtube video on README [https://github.com/nagarakesh4/TweetThis/blob/master/README.md#video-walkthrough](https://github.com/nagarakesh4/TweetThis/blob/master/README.md#video-walkthrough).

Here is the youtube URL [https://youtu.be/7fy_eqm7oDE]

**Comment by codepathreview** [comment]
:+1: Great work overall, @nagarakesh4 ! A few notes after checking out the code:

* Good to see you were able to format the timestamp cleanly 
* Good to see you refreshed the timeline after composing a new tweet
* Nice touch with the character count being displayed while the user composes a tweet
* Nice to see you used a `SwipeRefreshLayout` library for easy timeline refreshes
* Glad to see you made the compose activity into a dialog instead
* Great job embedding media image in tweet object
* Consider adding `ActiveAndroid` to the Tweet and User. See the [persistence guide](https://github.com/thecodepath/android_guides/wiki/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](https://github.com/thecodepath/android_guides/wiki/ActiveAndroid-Guide) for more details.
* Consider adding [progress bars] (http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
